# Используем образ с Node.js v22.13.1
FROM node:22.13.1

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY crud-backend/package*.json ./
RUN npm install

# Копируем остальные файлы проекта
COPY crud-backend ./

# Устанавливаем Prisma
RUN npx prisma generate

# Запускаем бэкенд
CMD ["npm", "run", "dev"]
