# Используем легкий базовый образ
FROM node:22.13.1-alpine as builder

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY crud-backend/package*.json ./
RUN npm install --production && npm cache clean --force

# Копируем остальные файлы проекта
COPY crud-backend ./

# Устанавливаем Prisma
RUN npx prisma generate

# Создаем финальный образ
FROM node:22.13.1-alpine

WORKDIR /app

# Копируем только нужные файлы из предыдущего этапа
COPY --from=builder /app /app

# Устанавливаем переменные окружения
ENV NODE_ENV=production

# Запускаем бэкенд
CMD ["npm", "run", "dev"]
