# Используем образ с Node.js
FROM node:18-alpine

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY crud-frontend/package*.json ./
RUN npm install

# Копируем остальные файлы проекта
COPY crud-frontend ./

# Строим проект
RUN npm run build

# Запускаем Vite на нужном порту
CMD ["npm", "run", "dev"]
