# Используем образ с Node.js
FROM node:22.13.1-bullseye-slim AS builder

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY crud-frontend/package*.json ./

# Удаляем package-lock.json, если он существует, чтобы избежать проблем с кэшированием зависимостей
RUN rm -f package-lock.json

# Устанавливаем зависимости с указанием архитектуры
RUN npm install --no-cache --arch=${TARGETARCH}

# Копируем весь код
COPY crud-frontend ./ 

# Собираем проект
RUN npm run build

# Финальный образ
FROM node:22.13.1-bullseye-slim AS final

WORKDIR /app

# Копируем приложение из сборки
COPY --from=builder /app /app

EXPOSE 5173

# Устанавливаем команду для запуска
CMD ["npm", "run", "dev"]
